name: school_schedule
description: Unofficial KronoX app

version: 3.9.0+309

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0
  flutter_markdown: ^0.2.0
  package_info: ^0.4.0+10
  path_provider: ^1.2.0
  html: ^0.14.0
  encrypt: ^3.2.0
  unique_identifier: ^0.0.3
  # These packages have a fixed version due to bugs with desktop support in newer versions
  shared_preferences: 0.5.4+9
  url_launcher: 5.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
