name: school_schedule
description: Unofficial KronoX app

version: 3.9.0+309

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.0
  flutter_markdown: ^0.6.0
  package_info: ^2.0.0
  path_provider: ^2.0.0
  html: ^0.15.0
  encrypt: ^5.0.0
  unique_identifier: ^0.2.0
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
